### ISSUE TITLE
Why is your website https://fattyalchemist.com/ a copy of @superguigui's website https://guillaumegouessan.com/ ?

### ISSUE THREAD

**Issue by MAKIO135** [mitdave95/whatsapp#1]
Why is your website https://fattyalchemist.com/ a copy of @superguigui's website https://guillaumegouessan.com/ ?

**Comment by superguigui** [comment]
@mitdave95 for the record if you need advice and help about setting up and designing your own website I'll be glad to help 🙌

**Comment by mitdave95** [comment]
@MAKIO135 @superguigui I have updated it, please check

@superguigui can you share you mail?
